pub struct Builder {
  handler_0: Option<String>,
  handler_1: Option<String>,
  handler_2: Option<String>,
  handler_3: Option<String>,
  handler_4: Option<String>,
  handler_5: Option<String>,
  handler_6: Option<String>,
  handler_7: Option<String>,
  handler_8: Option<String>,
  handler_9: Option<String>,
  handler_10: Option<String>,
  handler_11: Option<String>,
  handler_12: Option<String>,
  handler_13: Option<String>,
  handler_14: Option<String>,
  handler_15: Option<String>,
  handler_16: Option<String>,
  handler_17: Option<String>,
  handler_18: Option<String>,
  handler_19: Option<String>,
  handler_20: Option<String>,
  handler_21: Option<String>,
  handler_22: Option<String>,
  handler_23: Option<String>,
  handler_24: Option<String>,
  handler_25: Option<String>,
  handler_26: Option<String>,
  handler_27: Option<String>,
  handler_28: Option<String>,
  handler_29: Option<String>,
  handler_30: Option<String>,
  handler_31: Option<String>,
  handler_32: Option<String>,
  handler_33: Option<String>,
  handler_34: Option<String>,
  handler_35: Option<String>,
  handler_36: Option<String>,
  handler_37: Option<String>,
  handler_38: Option<String>,
  handler_39: Option<String>,
  handler_40: Option<String>,
  handler_41: Option<String>,
  handler_42: Option<String>,
  handler_43: Option<String>,
  handler_44: Option<String>,
  handler_45: Option<String>,
  handler_46: Option<String>,
  handler_47: Option<String>,
  handler_48: Option<String>,
  handler_49: Option<String>,
  handler_50: Option<String>,
  handler_51: Option<String>,
  handler_52: Option<String>,
  handler_53: Option<String>,
  handler_54: Option<String>,
  handler_55: Option<String>,
  handler_56: Option<String>,
  handler_57: Option<String>,
  handler_58: Option<String>,
  handler_59: Option<String>,
  handler_60: Option<String>,
  handler_61: Option<String>,
  handler_62: Option<String>,
  handler_63: Option<String>,
  handler_64: Option<String>,
  handler_65: Option<String>,
  handler_66: Option<String>,
  handler_67: Option<String>,
  handler_68: Option<String>,
  handler_69: Option<String>,
  handler_70: Option<String>,
  handler_71: Option<String>,
  handler_72: Option<String>,
  handler_73: Option<String>,
  handler_74: Option<String>,
  handler_75: Option<String>,
  handler_76: Option<String>,
  handler_77: Option<String>,
  handler_78: Option<String>,
  handler_79: Option<String>,
  handler_80: Option<String>,
  handler_81: Option<String>,
  handler_82: Option<String>,
  handler_83: Option<String>,
  handler_84: Option<String>,
  handler_85: Option<String>,
  handler_86: Option<String>,
  handler_87: Option<String>,
  handler_88: Option<String>,
  handler_89: Option<String>,
  handler_90: Option<String>,
  handler_91: Option<String>,
  handler_92: Option<String>,
  handler_93: Option<String>,
  handler_94: Option<String>,
  handler_95: Option<String>,
  handler_96: Option<String>,
  handler_97: Option<String>,
  handler_98: Option<String>,
  handler_99: Option<String>,
  handler_100: Option<String>,
  handler_101: Option<String>,
  handler_102: Option<String>,
  handler_103: Option<String>,
  handler_104: Option<String>,
  handler_105: Option<String>,
  handler_106: Option<String>,
  handler_107: Option<String>,
  handler_108: Option<String>,
  handler_109: Option<String>,
  handler_110: Option<String>,
  handler_111: Option<String>,
  handler_112: Option<String>,
  handler_113: Option<String>,
  handler_114: Option<String>,
  handler_115: Option<String>,
  handler_116: Option<String>,
  handler_117: Option<String>,
  handler_118: Option<String>,
  handler_119: Option<String>,
  handler_120: Option<String>,
  handler_121: Option<String>,
  handler_122: Option<String>,
  handler_123: Option<String>,
  handler_124: Option<String>,
  handler_125: Option<String>,
  handler_126: Option<String>,
  handler_127: Option<String>,
  handler_128: Option<String>,
  handler_129: Option<String>,
  handler_130: Option<String>,
  handler_131: Option<String>,
  handler_132: Option<String>,
  handler_133: Option<String>,
  handler_134: Option<String>,
  handler_135: Option<String>,
  handler_136: Option<String>,
  handler_137: Option<String>,
  handler_138: Option<String>,
  handler_139: Option<String>,
  handler_140: Option<String>,
  handler_141: Option<String>,
  handler_142: Option<String>,
  handler_143: Option<String>,
  handler_144: Option<String>,
  handler_145: Option<String>,
  handler_146: Option<String>,
  handler_147: Option<String>,
  handler_148: Option<String>,
  handler_149: Option<String>,
  handler_150: Option<String>,
  handler_151: Option<String>,
  handler_152: Option<String>,
  handler_153: Option<String>,
  handler_154: Option<String>,
  handler_155: Option<String>,
  handler_156: Option<String>,
  handler_157: Option<String>,
  handler_158: Option<String>,
  handler_159: Option<String>,
  handler_160: Option<String>,
  handler_161: Option<String>,
  handler_162: Option<String>,
  handler_163: Option<String>,
  handler_164: Option<String>,
  handler_165: Option<String>,
  handler_166: Option<String>,
  handler_167: Option<String>,
  handler_168: Option<String>,
  handler_169: Option<String>,
  handler_170: Option<String>,
  handler_171: Option<String>,
  handler_172: Option<String>,
  handler_173: Option<String>,
  handler_174: Option<String>,
  handler_175: Option<String>,
  handler_176: Option<String>,
  handler_177: Option<String>,
  handler_178: Option<String>,
  handler_179: Option<String>,
  handler_180: Option<String>,
  handler_181: Option<String>,
  handler_182: Option<String>,
  handler_183: Option<String>,
  handler_184: Option<String>,
  handler_185: Option<String>,
  handler_186: Option<String>,
  handler_187: Option<String>,
  handler_188: Option<String>,
  handler_189: Option<String>,
  handler_190: Option<String>,
  handler_191: Option<String>,
  handler_192: Option<String>,
  handler_193: Option<String>,
  handler_194: Option<String>,
  handler_195: Option<String>,
  handler_196: Option<String>,
  handler_197: Option<String>,
  handler_198: Option<String>,
  handler_199: Option<String>,
  handler_200: Option<String>,
  handler_201: Option<String>,
  handler_202: Option<String>,
  handler_203: Option<String>,
  handler_204: Option<String>,
  handler_205: Option<String>,
  handler_206: Option<String>,
  handler_207: Option<String>,
  handler_208: Option<String>,
  handler_209: Option<String>,
  handler_210: Option<String>,
  handler_211: Option<String>,
  handler_212: Option<String>,
  handler_213: Option<String>,
  handler_214: Option<String>,
  handler_215: Option<String>,
  handler_216: Option<String>,
  handler_217: Option<String>,
  handler_218: Option<String>,
  handler_219: Option<String>,
  handler_220: Option<String>,
  handler_221: Option<String>,
  handler_222: Option<String>,
  handler_223: Option<String>,
  handler_224: Option<String>,
  handler_225: Option<String>,
  handler_226: Option<String>,
  handler_227: Option<String>,
  handler_228: Option<String>,
  handler_229: Option<String>,
  handler_230: Option<String>,
  handler_231: Option<String>,
  handler_232: Option<String>,
  handler_233: Option<String>,
  handler_234: Option<String>,
  handler_235: Option<String>,
  handler_236: Option<String>,
  handler_237: Option<String>,
  handler_238: Option<String>,
  handler_239: Option<String>,
  handler_240: Option<String>,
  handler_241: Option<String>,
  handler_242: Option<String>,
  handler_243: Option<String>,
  handler_244: Option<String>,
  handler_245: Option<String>,
  handler_246: Option<String>,
  handler_247: Option<String>,
  handler_248: Option<String>,
  handler_249: Option<String>,
  handler_250: Option<String>,
  handler_251: Option<String>,
  handler_252: Option<String>,
  handler_253: Option<String>,
  handler_254: Option<String>,
  handler_255: Option<String>,
  handler_256: Option<String>,
  handler_257: Option<String>,
  handler_258: Option<String>,
  handler_259: Option<String>,
  handler_260: Option<String>,
  handler_261: Option<String>,
  handler_262: Option<String>,
  handler_263: Option<String>,
  handler_264: Option<String>,
  handler_265: Option<String>,
  handler_266: Option<String>,
  handler_267: Option<String>,
  handler_268: Option<String>,
  handler_269: Option<String>,
  handler_270: Option<String>,
  handler_271: Option<String>,
  handler_272: Option<String>,
  handler_273: Option<String>,
  handler_274: Option<String>,
  handler_275: Option<String>,
  handler_276: Option<String>,
  handler_277: Option<String>,
  handler_278: Option<String>,
  handler_279: Option<String>,
  handler_280: Option<String>,
  handler_281: Option<String>,
  handler_282: Option<String>,
  handler_283: Option<String>,
  handler_284: Option<String>,
  handler_285: Option<String>,
  handler_286: Option<String>,
  handler_287: Option<String>,
  handler_288: Option<String>,
  handler_289: Option<String>,
  handler_290: Option<String>,
  handler_291: Option<String>,
  handler_292: Option<String>,
  handler_293: Option<String>,
  handler_294: Option<String>,
  handler_295: Option<String>,
  handler_296: Option<String>,
  handler_297: Option<String>,
  handler_298: Option<String>,
  handler_299: Option<String>,
  handler_300: Option<String>,
  handler_301: Option<String>,
  handler_302: Option<String>,
  handler_303: Option<String>,
  handler_304: Option<String>,
  handler_305: Option<String>,
  handler_306: Option<String>,
  handler_307: Option<String>,
  handler_308: Option<String>,
  handler_309: Option<String>,
  handler_310: Option<String>,
  handler_311: Option<String>,
  handler_312: Option<String>,
  handler_313: Option<String>,
  handler_314: Option<String>,
  handler_315: Option<String>,
  handler_316: Option<String>,
  handler_317: Option<String>,
  handler_318: Option<String>,
  handler_319: Option<String>,
  handler_320: Option<String>,
  handler_321: Option<String>,
  handler_322: Option<String>,
  handler_323: Option<String>,
  handler_324: Option<String>,
  handler_325: Option<String>,
  handler_326: Option<String>,
  handler_327: Option<String>,
  handler_328: Option<String>,
  handler_329: Option<String>,
  handler_330: Option<String>,
  handler_331: Option<String>,
  handler_332: Option<String>,
  handler_333: Option<String>,
  handler_334: Option<String>,
  handler_335: Option<String>,
  handler_336: Option<String>,
  handler_337: Option<String>,
  handler_338: Option<String>,
  handler_339: Option<String>,
  handler_340: Option<String>,
  handler_341: Option<String>,
  handler_342: Option<String>,
  handler_343: Option<String>,
  handler_344: Option<String>,
  handler_345: Option<String>,
  handler_346: Option<String>,
  handler_347: Option<String>,
  handler_348: Option<String>,
  handler_349: Option<String>,
  handler_350: Option<String>,
  handler_351: Option<String>,
  handler_352: Option<String>,
  handler_353: Option<String>,
  handler_354: Option<String>,
  handler_355: Option<String>,
  handler_356: Option<String>,
  handler_357: Option<String>,
  handler_358: Option<String>,
  handler_359: Option<String>,
  handler_360: Option<String>,
  handler_361: Option<String>,
  handler_362: Option<String>,
  handler_363: Option<String>,
  handler_364: Option<String>,
  handler_365: Option<String>,
  handler_366: Option<String>,
  handler_367: Option<String>,
  handler_368: Option<String>,
  handler_369: Option<String>,
  handler_370: Option<String>,
  handler_371: Option<String>,
  handler_372: Option<String>,
  handler_373: Option<String>,
  handler_374: Option<String>,
  handler_375: Option<String>,
  handler_376: Option<String>,
  handler_377: Option<String>,
  handler_378: Option<String>,
  handler_379: Option<String>,
  handler_380: Option<String>,
  handler_381: Option<String>,
  handler_382: Option<String>,
  handler_383: Option<String>,
  handler_384: Option<String>,
  handler_385: Option<String>,
  handler_386: Option<String>,
  handler_387: Option<String>,
  handler_388: Option<String>,
  handler_389: Option<String>,
  handler_390: Option<String>,
  handler_391: Option<String>,
  handler_392: Option<String>,
  handler_393: Option<String>,
  handler_394: Option<String>,
  handler_395: Option<String>,
  handler_396: Option<String>,
  handler_397: Option<String>,
  handler_398: Option<String>,
  handler_399: Option<String>,
  handler_400: Option<String>,
  handler_401: Option<String>,
  handler_402: Option<String>,
  handler_403: Option<String>,
  handler_404: Option<String>,
  handler_405: Option<String>,
  handler_406: Option<String>,
  handler_407: Option<String>,
  handler_408: Option<String>,
  handler_409: Option<String>,
  handler_410: Option<String>,
  handler_411: Option<String>,
  handler_412: Option<String>,
  handler_413: Option<String>,
  handler_414: Option<String>,
  handler_415: Option<String>,
  handler_416: Option<String>,
  handler_417: Option<String>,
  handler_418: Option<String>,
  handler_419: Option<String>,
  handler_420: Option<String>,
  handler_421: Option<String>,
  handler_422: Option<String>,
  handler_423: Option<String>,
  handler_424: Option<String>,
  handler_425: Option<String>,
  handler_426: Option<String>,
  handler_427: Option<String>,
  handler_428: Option<String>,
  handler_429: Option<String>,
  handler_430: Option<String>,
  handler_431: Option<String>,
  handler_432: Option<String>,
  handler_433: Option<String>,
  handler_434: Option<String>,
  handler_435: Option<String>,
  handler_436: Option<String>,
  handler_437: Option<String>,
  handler_438: Option<String>,
  handler_439: Option<String>,
  handler_440: Option<String>,
  handler_441: Option<String>,
  handler_442: Option<String>,
  handler_443: Option<String>,
  handler_444: Option<String>,
  handler_445: Option<String>,
  handler_446: Option<String>,
  handler_447: Option<String>,
  handler_448: Option<String>,
  handler_449: Option<String>,
  handler_450: Option<String>,
  handler_451: Option<String>,
  handler_452: Option<String>,
  handler_453: Option<String>,
  handler_454: Option<String>,
  handler_455: Option<String>,
  handler_456: Option<String>,
  handler_457: Option<String>,
  handler_458: Option<String>,
  handler_459: Option<String>,
  handler_460: Option<String>,
  handler_461: Option<String>,
  handler_462: Option<String>,
  handler_463: Option<String>,
  handler_464: Option<String>,
  handler_465: Option<String>,
  handler_466: Option<String>,
  handler_467: Option<String>,
  handler_468: Option<String>,
  handler_469: Option<String>,
  handler_470: Option<String>,
  handler_471: Option<String>,
  handler_472: Option<String>,
  handler_473: Option<String>,
  handler_474: Option<String>,
  handler_475: Option<String>,
  handler_476: Option<String>,
  handler_477: Option<String>,
  handler_478: Option<String>,
  handler_479: Option<String>,
  handler_480: Option<String>,
  handler_481: Option<String>,
  handler_482: Option<String>,
  handler_483: Option<String>,
  handler_484: Option<String>,
  handler_485: Option<String>,
  handler_486: Option<String>,
  handler_487: Option<String>,
  handler_488: Option<String>,
  handler_489: Option<String>,
  handler_490: Option<String>,
  handler_491: Option<String>,
  handler_492: Option<String>,
  handler_493: Option<String>,
  handler_494: Option<String>,
  handler_495: Option<String>,
  handler_496: Option<String>,
  handler_497: Option<String>,
  handler_498: Option<String>,
  handler_499: Option<String>,
  handler_500: Option<String>,
  handler_501: Option<String>,
  handler_502: Option<String>,
  handler_503: Option<String>,
  handler_504: Option<String>,
  handler_505: Option<String>,
  handler_506: Option<String>,
  handler_507: Option<String>,
  handler_508: Option<String>,
  handler_509: Option<String>,
  handler_510: Option<String>,
  handler_511: Option<String>,
  handler_512: Option<String>,
  handler_513: Option<String>,
  handler_514: Option<String>,
  handler_515: Option<String>,
  handler_516: Option<String>,
  handler_517: Option<String>,
  handler_518: Option<String>,
  handler_519: Option<String>,
  handler_520: Option<String>,
  handler_521: Option<String>,
  handler_522: Option<String>,
  handler_523: Option<String>,
  handler_524: Option<String>,
  handler_525: Option<String>,
  handler_526: Option<String>,
  handler_527: Option<String>,
  handler_528: Option<String>,
  handler_529: Option<String>,
  handler_530: Option<String>,
  handler_531: Option<String>,
  handler_532: Option<String>,
  handler_533: Option<String>,
  handler_534: Option<String>,
  handler_535: Option<String>,
  handler_536: Option<String>,
  handler_537: Option<String>,
  handler_538: Option<String>,
  handler_539: Option<String>,
  handler_540: Option<String>,
  handler_541: Option<String>,
  handler_542: Option<String>,
  handler_543: Option<String>,
  handler_544: Option<String>,
  handler_545: Option<String>,
  handler_546: Option<String>,
  handler_547: Option<String>,
  handler_548: Option<String>,
  handler_549: Option<String>,
  handler_550: Option<String>,
  handler_551: Option<String>,
  handler_552: Option<String>,
  handler_553: Option<String>,
  handler_554: Option<String>,
  handler_555: Option<String>,
  handler_556: Option<String>,
  handler_557: Option<String>,
  handler_558: Option<String>,
  handler_559: Option<String>,
  handler_560: Option<String>,
  handler_561: Option<String>,
  handler_562: Option<String>,
  handler_563: Option<String>,
  handler_564: Option<String>,
  handler_565: Option<String>,
  handler_566: Option<String>,
  handler_567: Option<String>,
  handler_568: Option<String>,
  handler_569: Option<String>,
  handler_570: Option<String>,
  handler_571: Option<String>,
  handler_572: Option<String>,
  handler_573: Option<String>,
  handler_574: Option<String>,
  handler_575: Option<String>,
  handler_576: Option<String>,
  handler_577: Option<String>,
  handler_578: Option<String>,
  handler_579: Option<String>,
  handler_580: Option<String>,
  handler_581: Option<String>,
  handler_582: Option<String>,
  handler_583: Option<String>,
  handler_584: Option<String>,
  handler_585: Option<String>,
  handler_586: Option<String>,
  handler_587: Option<String>,
  handler_588: Option<String>,
  handler_589: Option<String>,
  handler_590: Option<String>,
  handler_591: Option<String>,
  handler_592: Option<String>,
  handler_593: Option<String>,
  handler_594: Option<String>,
  handler_595: Option<String>,
  handler_596: Option<String>,
  handler_597: Option<String>,
  handler_598: Option<String>,
  handler_599: Option<String>,
  handler_600: Option<String>,
  handler_601: Option<String>,
  handler_602: Option<String>,
  handler_603: Option<String>,
  handler_604: Option<String>,
  handler_605: Option<String>,
  handler_606: Option<String>,
  handler_607: Option<String>,
  handler_608: Option<String>,
  handler_609: Option<String>,
  handler_610: Option<String>,
  handler_611: Option<String>,
  handler_612: Option<String>,
  handler_613: Option<String>,
  handler_614: Option<String>,
  handler_615: Option<String>,
  handler_616: Option<String>,
  handler_617: Option<String>,
  handler_618: Option<String>,
  handler_619: Option<String>,
  handler_620: Option<String>,
}

impl Builder {
  pub fn trouble(self) -> usize {
    let endpoints = [
      self.handler_0.unwrap(),
      self.handler_1.unwrap(),
      self.handler_2.unwrap(),
      self.handler_3.unwrap(),
      self.handler_4.unwrap(),
      self.handler_5.unwrap(),
      self.handler_6.unwrap(),
      self.handler_7.unwrap(),
      self.handler_8.unwrap(),
      self.handler_9.unwrap(),
      self.handler_10.unwrap(),
      self.handler_11.unwrap(),
      self.handler_12.unwrap(),
      self.handler_13.unwrap(),
      self.handler_14.unwrap(),
      self.handler_15.unwrap(),
      self.handler_16.unwrap(),
      self.handler_17.unwrap(),
      self.handler_18.unwrap(),
      self.handler_19.unwrap(),
      self.handler_20.unwrap(),
      self.handler_21.unwrap(),
      self.handler_22.unwrap(),
      self.handler_23.unwrap(),
      self.handler_24.unwrap(),
      self.handler_25.unwrap(),
      self.handler_26.unwrap(),
      self.handler_27.unwrap(),
      self.handler_28.unwrap(),
      self.handler_29.unwrap(),
      self.handler_30.unwrap(),
      self.handler_31.unwrap(),
      self.handler_32.unwrap(),
      self.handler_33.unwrap(),
      self.handler_34.unwrap(),
      self.handler_35.unwrap(),
      self.handler_36.unwrap(),
      self.handler_37.unwrap(),
      self.handler_38.unwrap(),
      self.handler_39.unwrap(),
      self.handler_40.unwrap(),
      self.handler_41.unwrap(),
      self.handler_42.unwrap(),
      self.handler_43.unwrap(),
      self.handler_44.unwrap(),
      self.handler_45.unwrap(),
      self.handler_46.unwrap(),
      self.handler_47.unwrap(),
      self.handler_48.unwrap(),
      self.handler_49.unwrap(),
      self.handler_50.unwrap(),
      self.handler_51.unwrap(),
      self.handler_52.unwrap(),
      self.handler_53.unwrap(),
      self.handler_54.unwrap(),
      self.handler_55.unwrap(),
      self.handler_56.unwrap(),
      self.handler_57.unwrap(),
      self.handler_58.unwrap(),
      self.handler_59.unwrap(),
      self.handler_60.unwrap(),
      self.handler_61.unwrap(),
      self.handler_62.unwrap(),
      self.handler_63.unwrap(),
      self.handler_64.unwrap(),
      self.handler_65.unwrap(),
      self.handler_66.unwrap(),
      self.handler_67.unwrap(),
      self.handler_68.unwrap(),
      self.handler_69.unwrap(),
      self.handler_70.unwrap(),
      self.handler_71.unwrap(),
      self.handler_72.unwrap(),
      self.handler_73.unwrap(),
      self.handler_74.unwrap(),
      self.handler_75.unwrap(),
      self.handler_76.unwrap(),
      self.handler_77.unwrap(),
      self.handler_78.unwrap(),
      self.handler_79.unwrap(),
      self.handler_80.unwrap(),
      self.handler_81.unwrap(),
      self.handler_82.unwrap(),
      self.handler_83.unwrap(),
      self.handler_84.unwrap(),
      self.handler_85.unwrap(),
      self.handler_86.unwrap(),
      self.handler_87.unwrap(),
      self.handler_88.unwrap(),
      self.handler_89.unwrap(),
      self.handler_90.unwrap(),
      self.handler_91.unwrap(),
      self.handler_92.unwrap(),
      self.handler_93.unwrap(),
      self.handler_94.unwrap(),
      self.handler_95.unwrap(),
      self.handler_96.unwrap(),
      self.handler_97.unwrap(),
      self.handler_98.unwrap(),
      self.handler_99.unwrap(),
      self.handler_100.unwrap(),
      self.handler_101.unwrap(),
      self.handler_102.unwrap(),
      self.handler_103.unwrap(),
      self.handler_104.unwrap(),
      self.handler_105.unwrap(),
      self.handler_106.unwrap(),
      self.handler_107.unwrap(),
      self.handler_108.unwrap(),
      self.handler_109.unwrap(),
      self.handler_110.unwrap(),
      self.handler_111.unwrap(),
      self.handler_112.unwrap(),
      self.handler_113.unwrap(),
      self.handler_114.unwrap(),
      self.handler_115.unwrap(),
      self.handler_116.unwrap(),
      self.handler_117.unwrap(),
      self.handler_118.unwrap(),
      self.handler_119.unwrap(),
      self.handler_120.unwrap(),
      self.handler_121.unwrap(),
      self.handler_122.unwrap(),
      self.handler_123.unwrap(),
      self.handler_124.unwrap(),
      self.handler_125.unwrap(),
      self.handler_126.unwrap(),
      self.handler_127.unwrap(),
      self.handler_128.unwrap(),
      self.handler_129.unwrap(),
      self.handler_130.unwrap(),
      self.handler_131.unwrap(),
      self.handler_132.unwrap(),
      self.handler_133.unwrap(),
      self.handler_134.unwrap(),
      self.handler_135.unwrap(),
      self.handler_136.unwrap(),
      self.handler_137.unwrap(),
      self.handler_138.unwrap(),
      self.handler_139.unwrap(),
      self.handler_140.unwrap(),
      self.handler_141.unwrap(),
      self.handler_142.unwrap(),
      self.handler_143.unwrap(),
      self.handler_144.unwrap(),
      self.handler_145.unwrap(),
      self.handler_146.unwrap(),
      self.handler_147.unwrap(),
      self.handler_148.unwrap(),
      self.handler_149.unwrap(),
      self.handler_150.unwrap(),
      self.handler_151.unwrap(),
      self.handler_152.unwrap(),
      self.handler_153.unwrap(),
      self.handler_154.unwrap(),
      self.handler_155.unwrap(),
      self.handler_156.unwrap(),
      self.handler_157.unwrap(),
      self.handler_158.unwrap(),
      self.handler_159.unwrap(),
      self.handler_160.unwrap(),
      self.handler_161.unwrap(),
      self.handler_162.unwrap(),
      self.handler_163.unwrap(),
      self.handler_164.unwrap(),
      self.handler_165.unwrap(),
      self.handler_166.unwrap(),
      self.handler_167.unwrap(),
      self.handler_168.unwrap(),
      self.handler_169.unwrap(),
      self.handler_170.unwrap(),
      self.handler_171.unwrap(),
      self.handler_172.unwrap(),
      self.handler_173.unwrap(),
      self.handler_174.unwrap(),
      self.handler_175.unwrap(),
      self.handler_176.unwrap(),
      self.handler_177.unwrap(),
      self.handler_178.unwrap(),
      self.handler_179.unwrap(),
      self.handler_180.unwrap(),
      self.handler_181.unwrap(),
      self.handler_182.unwrap(),
      self.handler_183.unwrap(),
      self.handler_184.unwrap(),
      self.handler_185.unwrap(),
      self.handler_186.unwrap(),
      self.handler_187.unwrap(),
      self.handler_188.unwrap(),
      self.handler_189.unwrap(),
      self.handler_190.unwrap(),
      self.handler_191.unwrap(),
      self.handler_192.unwrap(),
      self.handler_193.unwrap(),
      self.handler_194.unwrap(),
      self.handler_195.unwrap(),
      self.handler_196.unwrap(),
      self.handler_197.unwrap(),
      self.handler_198.unwrap(),
      self.handler_199.unwrap(),
      self.handler_200.unwrap(),
      self.handler_201.unwrap(),
      self.handler_202.unwrap(),
      self.handler_203.unwrap(),
      self.handler_204.unwrap(),
      self.handler_205.unwrap(),
      self.handler_206.unwrap(),
      self.handler_207.unwrap(),
      self.handler_208.unwrap(),
      self.handler_209.unwrap(),
      self.handler_210.unwrap(),
      self.handler_211.unwrap(),
      self.handler_212.unwrap(),
      self.handler_213.unwrap(),
      self.handler_214.unwrap(),
      self.handler_215.unwrap(),
      self.handler_216.unwrap(),
      self.handler_217.unwrap(),
      self.handler_218.unwrap(),
      self.handler_219.unwrap(),
      self.handler_220.unwrap(),
      self.handler_221.unwrap(),
      self.handler_222.unwrap(),
      self.handler_223.unwrap(),
      self.handler_224.unwrap(),
      self.handler_225.unwrap(),
      self.handler_226.unwrap(),
      self.handler_227.unwrap(),
      self.handler_228.unwrap(),
      self.handler_229.unwrap(),
      self.handler_230.unwrap(),
      self.handler_231.unwrap(),
      self.handler_232.unwrap(),
      self.handler_233.unwrap(),
      self.handler_234.unwrap(),
      self.handler_235.unwrap(),
      self.handler_236.unwrap(),
      self.handler_237.unwrap(),
      self.handler_238.unwrap(),
      self.handler_239.unwrap(),
      self.handler_240.unwrap(),
      self.handler_241.unwrap(),
      self.handler_242.unwrap(),
      self.handler_243.unwrap(),
      self.handler_244.unwrap(),
      self.handler_245.unwrap(),
      self.handler_246.unwrap(),
      self.handler_247.unwrap(),
      self.handler_248.unwrap(),
      self.handler_249.unwrap(),
      self.handler_250.unwrap(),
      self.handler_251.unwrap(),
      self.handler_252.unwrap(),
      self.handler_253.unwrap(),
      self.handler_254.unwrap(),
      self.handler_255.unwrap(),
      self.handler_256.unwrap(),
      self.handler_257.unwrap(),
      self.handler_258.unwrap(),
      self.handler_259.unwrap(),
      self.handler_260.unwrap(),
      self.handler_261.unwrap(),
      self.handler_262.unwrap(),
      self.handler_263.unwrap(),
      self.handler_264.unwrap(),
      self.handler_265.unwrap(),
      self.handler_266.unwrap(),
      self.handler_267.unwrap(),
      self.handler_268.unwrap(),
      self.handler_269.unwrap(),
      self.handler_270.unwrap(),
      self.handler_271.unwrap(),
      self.handler_272.unwrap(),
      self.handler_273.unwrap(),
      self.handler_274.unwrap(),
      self.handler_275.unwrap(),
      self.handler_276.unwrap(),
      self.handler_277.unwrap(),
      self.handler_278.unwrap(),
      self.handler_279.unwrap(),
      self.handler_280.unwrap(),
      self.handler_281.unwrap(),
      self.handler_282.unwrap(),
      self.handler_283.unwrap(),
      self.handler_284.unwrap(),
      self.handler_285.unwrap(),
      self.handler_286.unwrap(),
      self.handler_287.unwrap(),
      self.handler_288.unwrap(),
      self.handler_289.unwrap(),
      self.handler_290.unwrap(),
      self.handler_291.unwrap(),
      self.handler_292.unwrap(),
      self.handler_293.unwrap(),
      self.handler_294.unwrap(),
      self.handler_295.unwrap(),
      self.handler_296.unwrap(),
      self.handler_297.unwrap(),
      self.handler_298.unwrap(),
      self.handler_299.unwrap(),
      self.handler_300.unwrap(),
      self.handler_301.unwrap(),
      self.handler_302.unwrap(),
      self.handler_303.unwrap(),
      self.handler_304.unwrap(),
      self.handler_305.unwrap(),
      self.handler_306.unwrap(),
      self.handler_307.unwrap(),
      self.handler_308.unwrap(),
      self.handler_309.unwrap(),
      self.handler_310.unwrap(),
      self.handler_311.unwrap(),
      self.handler_312.unwrap(),
      self.handler_313.unwrap(),
      self.handler_314.unwrap(),
      self.handler_315.unwrap(),
      self.handler_316.unwrap(),
      self.handler_317.unwrap(),
      self.handler_318.unwrap(),
      self.handler_319.unwrap(),
      self.handler_320.unwrap(),
      self.handler_321.unwrap(),
      self.handler_322.unwrap(),
      self.handler_323.unwrap(),
      self.handler_324.unwrap(),
      self.handler_325.unwrap(),
      self.handler_326.unwrap(),
      self.handler_327.unwrap(),
      self.handler_328.unwrap(),
      self.handler_329.unwrap(),
      self.handler_330.unwrap(),
      self.handler_331.unwrap(),
      self.handler_332.unwrap(),
      self.handler_333.unwrap(),
      self.handler_334.unwrap(),
      self.handler_335.unwrap(),
      self.handler_336.unwrap(),
      self.handler_337.unwrap(),
      self.handler_338.unwrap(),
      self.handler_339.unwrap(),
      self.handler_340.unwrap(),
      self.handler_341.unwrap(),
      self.handler_342.unwrap(),
      self.handler_343.unwrap(),
      self.handler_344.unwrap(),
      self.handler_345.unwrap(),
      self.handler_346.unwrap(),
      self.handler_347.unwrap(),
      self.handler_348.unwrap(),
      self.handler_349.unwrap(),
      self.handler_350.unwrap(),
      self.handler_351.unwrap(),
      self.handler_352.unwrap(),
      self.handler_353.unwrap(),
      self.handler_354.unwrap(),
      self.handler_355.unwrap(),
      self.handler_356.unwrap(),
      self.handler_357.unwrap(),
      self.handler_358.unwrap(),
      self.handler_359.unwrap(),
      self.handler_360.unwrap(),
      self.handler_361.unwrap(),
      self.handler_362.unwrap(),
      self.handler_363.unwrap(),
      self.handler_364.unwrap(),
      self.handler_365.unwrap(),
      self.handler_366.unwrap(),
      self.handler_367.unwrap(),
      self.handler_368.unwrap(),
      self.handler_369.unwrap(),
      self.handler_370.unwrap(),
      self.handler_371.unwrap(),
      self.handler_372.unwrap(),
      self.handler_373.unwrap(),
      self.handler_374.unwrap(),
      self.handler_375.unwrap(),
      self.handler_376.unwrap(),
      self.handler_377.unwrap(),
      self.handler_378.unwrap(),
      self.handler_379.unwrap(),
      self.handler_380.unwrap(),
      self.handler_381.unwrap(),
      self.handler_382.unwrap(),
      self.handler_383.unwrap(),
      self.handler_384.unwrap(),
      self.handler_385.unwrap(),
      self.handler_386.unwrap(),
      self.handler_387.unwrap(),
      self.handler_388.unwrap(),
      self.handler_389.unwrap(),
      self.handler_390.unwrap(),
      self.handler_391.unwrap(),
      self.handler_392.unwrap(),
      self.handler_393.unwrap(),
      self.handler_394.unwrap(),
      self.handler_395.unwrap(),
      self.handler_396.unwrap(),
      self.handler_397.unwrap(),
      self.handler_398.unwrap(),
      self.handler_399.unwrap(),
      self.handler_400.unwrap(),
      self.handler_401.unwrap(),
      self.handler_402.unwrap(),
      self.handler_403.unwrap(),
      self.handler_404.unwrap(),
      self.handler_405.unwrap(),
      self.handler_406.unwrap(),
      self.handler_407.unwrap(),
      self.handler_408.unwrap(),
      self.handler_409.unwrap(),
      self.handler_410.unwrap(),
      self.handler_411.unwrap(),
      self.handler_412.unwrap(),
      self.handler_413.unwrap(),
      self.handler_414.unwrap(),
      self.handler_415.unwrap(),
      self.handler_416.unwrap(),
      self.handler_417.unwrap(),
      self.handler_418.unwrap(),
      self.handler_419.unwrap(),
      self.handler_420.unwrap(),
      self.handler_421.unwrap(),
      self.handler_422.unwrap(),
      self.handler_423.unwrap(),
      self.handler_424.unwrap(),
      self.handler_425.unwrap(),
      self.handler_426.unwrap(),
      self.handler_427.unwrap(),
      self.handler_428.unwrap(),
      self.handler_429.unwrap(),
      self.handler_430.unwrap(),
      self.handler_431.unwrap(),
      self.handler_432.unwrap(),
      self.handler_433.unwrap(),
      self.handler_434.unwrap(),
      self.handler_435.unwrap(),
      self.handler_436.unwrap(),
      self.handler_437.unwrap(),
      self.handler_438.unwrap(),
      self.handler_439.unwrap(),
      self.handler_440.unwrap(),
      self.handler_441.unwrap(),
      self.handler_442.unwrap(),
      self.handler_443.unwrap(),
      self.handler_444.unwrap(),
      self.handler_445.unwrap(),
      self.handler_446.unwrap(),
      self.handler_447.unwrap(),
      self.handler_448.unwrap(),
      self.handler_449.unwrap(),
      self.handler_450.unwrap(),
      self.handler_451.unwrap(),
      self.handler_452.unwrap(),
      self.handler_453.unwrap(),
      self.handler_454.unwrap(),
      self.handler_455.unwrap(),
      self.handler_456.unwrap(),
      self.handler_457.unwrap(),
      self.handler_458.unwrap(),
      self.handler_459.unwrap(),
      self.handler_460.unwrap(),
      self.handler_461.unwrap(),
      self.handler_462.unwrap(),
      self.handler_463.unwrap(),
      self.handler_464.unwrap(),
      self.handler_465.unwrap(),
      self.handler_466.unwrap(),
      self.handler_467.unwrap(),
      self.handler_468.unwrap(),
      self.handler_469.unwrap(),
      self.handler_470.unwrap(),
      self.handler_471.unwrap(),
      self.handler_472.unwrap(),
      self.handler_473.unwrap(),
      self.handler_474.unwrap(),
      self.handler_475.unwrap(),
      self.handler_476.unwrap(),
      self.handler_477.unwrap(),
      self.handler_478.unwrap(),
      self.handler_479.unwrap(),
      self.handler_480.unwrap(),
      self.handler_481.unwrap(),
      self.handler_482.unwrap(),
      self.handler_483.unwrap(),
      self.handler_484.unwrap(),
      self.handler_485.unwrap(),
      self.handler_486.unwrap(),
      self.handler_487.unwrap(),
      self.handler_488.unwrap(),
      self.handler_489.unwrap(),
      self.handler_490.unwrap(),
      self.handler_491.unwrap(),
      self.handler_492.unwrap(),
      self.handler_493.unwrap(),
      self.handler_494.unwrap(),
      self.handler_495.unwrap(),
      self.handler_496.unwrap(),
      self.handler_497.unwrap(),
      self.handler_498.unwrap(),
      self.handler_499.unwrap(),
      self.handler_500.unwrap(),
      self.handler_501.unwrap(),
      self.handler_502.unwrap(),
      self.handler_503.unwrap(),
      self.handler_504.unwrap(),
      self.handler_505.unwrap(),
      self.handler_506.unwrap(),
      self.handler_507.unwrap(),
      self.handler_508.unwrap(),
      self.handler_509.unwrap(),
      self.handler_510.unwrap(),
      self.handler_511.unwrap(),
      self.handler_512.unwrap(),
      self.handler_513.unwrap(),
      self.handler_514.unwrap(),
      self.handler_515.unwrap(),
      self.handler_516.unwrap(),
      self.handler_517.unwrap(),
      self.handler_518.unwrap(),
      self.handler_519.unwrap(),
      self.handler_520.unwrap(),
      self.handler_521.unwrap(),
      self.handler_522.unwrap(),
      self.handler_523.unwrap(),
      self.handler_524.unwrap(),
      self.handler_525.unwrap(),
      self.handler_526.unwrap(),
      self.handler_527.unwrap(),
      self.handler_528.unwrap(),
      self.handler_529.unwrap(),
      self.handler_530.unwrap(),
      self.handler_531.unwrap(),
      self.handler_532.unwrap(),
      self.handler_533.unwrap(),
      self.handler_534.unwrap(),
      self.handler_535.unwrap(),
      self.handler_536.unwrap(),
      self.handler_537.unwrap(),
      self.handler_538.unwrap(),
      self.handler_539.unwrap(),
      self.handler_540.unwrap(),
      self.handler_541.unwrap(),
      self.handler_542.unwrap(),
      self.handler_543.unwrap(),
      self.handler_544.unwrap(),
      self.handler_545.unwrap(),
      self.handler_546.unwrap(),
      self.handler_547.unwrap(),
      self.handler_548.unwrap(),
      self.handler_549.unwrap(),
      self.handler_550.unwrap(),
      self.handler_551.unwrap(),
      self.handler_552.unwrap(),
      self.handler_553.unwrap(),
      self.handler_554.unwrap(),
      self.handler_555.unwrap(),
      self.handler_556.unwrap(),
      self.handler_557.unwrap(),
      self.handler_558.unwrap(),
      self.handler_559.unwrap(),
      self.handler_560.unwrap(),
      self.handler_561.unwrap(),
      self.handler_562.unwrap(),
      self.handler_563.unwrap(),
      self.handler_564.unwrap(),
      self.handler_565.unwrap(),
      self.handler_566.unwrap(),
      self.handler_567.unwrap(),
      self.handler_568.unwrap(),
      self.handler_569.unwrap(),
      self.handler_570.unwrap(),
      self.handler_571.unwrap(),
      self.handler_572.unwrap(),
      self.handler_573.unwrap(),
      self.handler_574.unwrap(),
      self.handler_575.unwrap(),
      self.handler_576.unwrap(),
      self.handler_577.unwrap(),
      self.handler_578.unwrap(),
      self.handler_579.unwrap(),
      self.handler_580.unwrap(),
      self.handler_581.unwrap(),
      self.handler_582.unwrap(),
      self.handler_583.unwrap(),
      self.handler_584.unwrap(),
      self.handler_585.unwrap(),
      self.handler_586.unwrap(),
      self.handler_587.unwrap(),
      self.handler_588.unwrap(),
      self.handler_589.unwrap(),
      self.handler_590.unwrap(),
      self.handler_591.unwrap(),
      self.handler_592.unwrap(),
      self.handler_593.unwrap(),
      self.handler_594.unwrap(),
      self.handler_595.unwrap(),
      self.handler_596.unwrap(),
      self.handler_597.unwrap(),
      self.handler_598.unwrap(),
      self.handler_599.unwrap(),
      self.handler_600.unwrap(),
      self.handler_601.unwrap(),
      self.handler_602.unwrap(),
      self.handler_603.unwrap(),
      self.handler_604.unwrap(),
      self.handler_605.unwrap(),
      self.handler_606.unwrap(),
      self.handler_607.unwrap(),
      self.handler_608.unwrap(),
      self.handler_609.unwrap(),
      self.handler_610.unwrap(),
      self.handler_611.unwrap(),
      self.handler_612.unwrap(),
      self.handler_613.unwrap(),
      self.handler_614.unwrap(),
      self.handler_615.unwrap(),
      self.handler_616.unwrap(),
      self.handler_617.unwrap(),
      self.handler_618.unwrap(),
      self.handler_619.unwrap(),
      self.handler_620.unwrap(),
    ];
    endpoints.len()
  }
}

impl Builder {
  pub fn builder() -> Builder {
    Builder {
      handler_0: None,
      handler_1: None,
      handler_2: None,
      handler_3: None,
      handler_4: None,
      handler_5: None,
      handler_6: None,
      handler_7: None,
      handler_8: None,
      handler_9: None,
      handler_10: None,
      handler_11: None,
      handler_12: None,
      handler_13: None,
      handler_14: None,
      handler_15: None,
      handler_16: None,
      handler_17: None,
      handler_18: None,
      handler_19: None,
      handler_20: None,
      handler_21: None,
      handler_22: None,
      handler_23: None,
      handler_24: None,
      handler_25: None,
      handler_26: None,
      handler_27: None,
      handler_28: None,
      handler_29: None,
      handler_30: None,
      handler_31: None,
      handler_32: None,
      handler_33: None,
      handler_34: None,
      handler_35: None,
      handler_36: None,
      handler_37: None,
      handler_38: None,
      handler_39: None,
      handler_40: None,
      handler_41: None,
      handler_42: None,
      handler_43: None,
      handler_44: None,
      handler_45: None,
      handler_46: None,
      handler_47: None,
      handler_48: None,
      handler_49: None,
      handler_50: None,
      handler_51: None,
      handler_52: None,
      handler_53: None,
      handler_54: None,
      handler_55: None,
      handler_56: None,
      handler_57: None,
      handler_58: None,
      handler_59: None,
      handler_60: None,
      handler_61: None,
      handler_62: None,
      handler_63: None,
      handler_64: None,
      handler_65: None,
      handler_66: None,
      handler_67: None,
      handler_68: None,
      handler_69: None,
      handler_70: None,
      handler_71: None,
      handler_72: None,
      handler_73: None,
      handler_74: None,
      handler_75: None,
      handler_76: None,
      handler_77: None,
      handler_78: None,
      handler_79: None,
      handler_80: None,
      handler_81: None,
      handler_82: None,
      handler_83: None,
      handler_84: None,
      handler_85: None,
      handler_86: None,
      handler_87: None,
      handler_88: None,
      handler_89: None,
      handler_90: None,
      handler_91: None,
      handler_92: None,
      handler_93: None,
      handler_94: None,
      handler_95: None,
      handler_96: None,
      handler_97: None,
      handler_98: None,
      handler_99: None,
      handler_100: None,
      handler_101: None,
      handler_102: None,
      handler_103: None,
      handler_104: None,
      handler_105: None,
      handler_106: None,
      handler_107: None,
      handler_108: None,
      handler_109: None,
      handler_110: None,
      handler_111: None,
      handler_112: None,
      handler_113: None,
      handler_114: None,
      handler_115: None,
      handler_116: None,
      handler_117: None,
      handler_118: None,
      handler_119: None,
      handler_120: None,
      handler_121: None,
      handler_122: None,
      handler_123: None,
      handler_124: None,
      handler_125: None,
      handler_126: None,
      handler_127: None,
      handler_128: None,
      handler_129: None,
      handler_130: None,
      handler_131: None,
      handler_132: None,
      handler_133: None,
      handler_134: None,
      handler_135: None,
      handler_136: None,
      handler_137: None,
      handler_138: None,
      handler_139: None,
      handler_140: None,
      handler_141: None,
      handler_142: None,
      handler_143: None,
      handler_144: None,
      handler_145: None,
      handler_146: None,
      handler_147: None,
      handler_148: None,
      handler_149: None,
      handler_150: None,
      handler_151: None,
      handler_152: None,
      handler_153: None,
      handler_154: None,
      handler_155: None,
      handler_156: None,
      handler_157: None,
      handler_158: None,
      handler_159: None,
      handler_160: None,
      handler_161: None,
      handler_162: None,
      handler_163: None,
      handler_164: None,
      handler_165: None,
      handler_166: None,
      handler_167: None,
      handler_168: None,
      handler_169: None,
      handler_170: None,
      handler_171: None,
      handler_172: None,
      handler_173: None,
      handler_174: None,
      handler_175: None,
      handler_176: None,
      handler_177: None,
      handler_178: None,
      handler_179: None,
      handler_180: None,
      handler_181: None,
      handler_182: None,
      handler_183: None,
      handler_184: None,
      handler_185: None,
      handler_186: None,
      handler_187: None,
      handler_188: None,
      handler_189: None,
      handler_190: None,
      handler_191: None,
      handler_192: None,
      handler_193: None,
      handler_194: None,
      handler_195: None,
      handler_196: None,
      handler_197: None,
      handler_198: None,
      handler_199: None,
      handler_200: None,
      handler_201: None,
      handler_202: None,
      handler_203: None,
      handler_204: None,
      handler_205: None,
      handler_206: None,
      handler_207: None,
      handler_208: None,
      handler_209: None,
      handler_210: None,
      handler_211: None,
      handler_212: None,
      handler_213: None,
      handler_214: None,
      handler_215: None,
      handler_216: None,
      handler_217: None,
      handler_218: None,
      handler_219: None,
      handler_220: None,
      handler_221: None,
      handler_222: None,
      handler_223: None,
      handler_224: None,
      handler_225: None,
      handler_226: None,
      handler_227: None,
      handler_228: None,
      handler_229: None,
      handler_230: None,
      handler_231: None,
      handler_232: None,
      handler_233: None,
      handler_234: None,
      handler_235: None,
      handler_236: None,
      handler_237: None,
      handler_238: None,
      handler_239: None,
      handler_240: None,
      handler_241: None,
      handler_242: None,
      handler_243: None,
      handler_244: None,
      handler_245: None,
      handler_246: None,
      handler_247: None,
      handler_248: None,
      handler_249: None,
      handler_250: None,
      handler_251: None,
      handler_252: None,
      handler_253: None,
      handler_254: None,
      handler_255: None,
      handler_256: None,
      handler_257: None,
      handler_258: None,
      handler_259: None,
      handler_260: None,
      handler_261: None,
      handler_262: None,
      handler_263: None,
      handler_264: None,
      handler_265: None,
      handler_266: None,
      handler_267: None,
      handler_268: None,
      handler_269: None,
      handler_270: None,
      handler_271: None,
      handler_272: None,
      handler_273: None,
      handler_274: None,
      handler_275: None,
      handler_276: None,
      handler_277: None,
      handler_278: None,
      handler_279: None,
      handler_280: None,
      handler_281: None,
      handler_282: None,
      handler_283: None,
      handler_284: None,
      handler_285: None,
      handler_286: None,
      handler_287: None,
      handler_288: None,
      handler_289: None,
      handler_290: None,
      handler_291: None,
      handler_292: None,
      handler_293: None,
      handler_294: None,
      handler_295: None,
      handler_296: None,
      handler_297: None,
      handler_298: None,
      handler_299: None,
      handler_300: None,
      handler_301: None,
      handler_302: None,
      handler_303: None,
      handler_304: None,
      handler_305: None,
      handler_306: None,
      handler_307: None,
      handler_308: None,
      handler_309: None,
      handler_310: None,
      handler_311: None,
      handler_312: None,
      handler_313: None,
      handler_314: None,
      handler_315: None,
      handler_316: None,
      handler_317: None,
      handler_318: None,
      handler_319: None,
      handler_320: None,
      handler_321: None,
      handler_322: None,
      handler_323: None,
      handler_324: None,
      handler_325: None,
      handler_326: None,
      handler_327: None,
      handler_328: None,
      handler_329: None,
      handler_330: None,
      handler_331: None,
      handler_332: None,
      handler_333: None,
      handler_334: None,
      handler_335: None,
      handler_336: None,
      handler_337: None,
      handler_338: None,
      handler_339: None,
      handler_340: None,
      handler_341: None,
      handler_342: None,
      handler_343: None,
      handler_344: None,
      handler_345: None,
      handler_346: None,
      handler_347: None,
      handler_348: None,
      handler_349: None,
      handler_350: None,
      handler_351: None,
      handler_352: None,
      handler_353: None,
      handler_354: None,
      handler_355: None,
      handler_356: None,
      handler_357: None,
      handler_358: None,
      handler_359: None,
      handler_360: None,
      handler_361: None,
      handler_362: None,
      handler_363: None,
      handler_364: None,
      handler_365: None,
      handler_366: None,
      handler_367: None,
      handler_368: None,
      handler_369: None,
      handler_370: None,
      handler_371: None,
      handler_372: None,
      handler_373: None,
      handler_374: None,
      handler_375: None,
      handler_376: None,
      handler_377: None,
      handler_378: None,
      handler_379: None,
      handler_380: None,
      handler_381: None,
      handler_382: None,
      handler_383: None,
      handler_384: None,
      handler_385: None,
      handler_386: None,
      handler_387: None,
      handler_388: None,
      handler_389: None,
      handler_390: None,
      handler_391: None,
      handler_392: None,
      handler_393: None,
      handler_394: None,
      handler_395: None,
      handler_396: None,
      handler_397: None,
      handler_398: None,
      handler_399: None,
      handler_400: None,
      handler_401: None,
      handler_402: None,
      handler_403: None,
      handler_404: None,
      handler_405: None,
      handler_406: None,
      handler_407: None,
      handler_408: None,
      handler_409: None,
      handler_410: None,
      handler_411: None,
      handler_412: None,
      handler_413: None,
      handler_414: None,
      handler_415: None,
      handler_416: None,
      handler_417: None,
      handler_418: None,
      handler_419: None,
      handler_420: None,
      handler_421: None,
      handler_422: None,
      handler_423: None,
      handler_424: None,
      handler_425: None,
      handler_426: None,
      handler_427: None,
      handler_428: None,
      handler_429: None,
      handler_430: None,
      handler_431: None,
      handler_432: None,
      handler_433: None,
      handler_434: None,
      handler_435: None,
      handler_436: None,
      handler_437: None,
      handler_438: None,
      handler_439: None,
      handler_440: None,
      handler_441: None,
      handler_442: None,
      handler_443: None,
      handler_444: None,
      handler_445: None,
      handler_446: None,
      handler_447: None,
      handler_448: None,
      handler_449: None,
      handler_450: None,
      handler_451: None,
      handler_452: None,
      handler_453: None,
      handler_454: None,
      handler_455: None,
      handler_456: None,
      handler_457: None,
      handler_458: None,
      handler_459: None,
      handler_460: None,
      handler_461: None,
      handler_462: None,
      handler_463: None,
      handler_464: None,
      handler_465: None,
      handler_466: None,
      handler_467: None,
      handler_468: None,
      handler_469: None,
      handler_470: None,
      handler_471: None,
      handler_472: None,
      handler_473: None,
      handler_474: None,
      handler_475: None,
      handler_476: None,
      handler_477: None,
      handler_478: None,
      handler_479: None,
      handler_480: None,
      handler_481: None,
      handler_482: None,
      handler_483: None,
      handler_484: None,
      handler_485: None,
      handler_486: None,
      handler_487: None,
      handler_488: None,
      handler_489: None,
      handler_490: None,
      handler_491: None,
      handler_492: None,
      handler_493: None,
      handler_494: None,
      handler_495: None,
      handler_496: None,
      handler_497: None,
      handler_498: None,
      handler_499: None,
      handler_500: None,
      handler_501: None,
      handler_502: None,
      handler_503: None,
      handler_504: None,
      handler_505: None,
      handler_506: None,
      handler_507: None,
      handler_508: None,
      handler_509: None,
      handler_510: None,
      handler_511: None,
      handler_512: None,
      handler_513: None,
      handler_514: None,
      handler_515: None,
      handler_516: None,
      handler_517: None,
      handler_518: None,
      handler_519: None,
      handler_520: None,
      handler_521: None,
      handler_522: None,
      handler_523: None,
      handler_524: None,
      handler_525: None,
      handler_526: None,
      handler_527: None,
      handler_528: None,
      handler_529: None,
      handler_530: None,
      handler_531: None,
      handler_532: None,
      handler_533: None,
      handler_534: None,
      handler_535: None,
      handler_536: None,
      handler_537: None,
      handler_538: None,
      handler_539: None,
      handler_540: None,
      handler_541: None,
      handler_542: None,
      handler_543: None,
      handler_544: None,
      handler_545: None,
      handler_546: None,
      handler_547: None,
      handler_548: None,
      handler_549: None,
      handler_550: None,
      handler_551: None,
      handler_552: None,
      handler_553: None,
      handler_554: None,
      handler_555: None,
      handler_556: None,
      handler_557: None,
      handler_558: None,
      handler_559: None,
      handler_560: None,
      handler_561: None,
      handler_562: None,
      handler_563: None,
      handler_564: None,
      handler_565: None,
      handler_566: None,
      handler_567: None,
      handler_568: None,
      handler_569: None,
      handler_570: None,
      handler_571: None,
      handler_572: None,
      handler_573: None,
      handler_574: None,
      handler_575: None,
      handler_576: None,
      handler_577: None,
      handler_578: None,
      handler_579: None,
      handler_580: None,
      handler_581: None,
      handler_582: None,
      handler_583: None,
      handler_584: None,
      handler_585: None,
      handler_586: None,
      handler_587: None,
      handler_588: None,
      handler_589: None,
      handler_590: None,
      handler_591: None,
      handler_592: None,
      handler_593: None,
      handler_594: None,
      handler_595: None,
      handler_596: None,
      handler_597: None,
      handler_598: None,
      handler_599: None,
      handler_600: None,
      handler_601: None,
      handler_602: None,
      handler_603: None,
      handler_604: None,
      handler_605: None,
      handler_606: None,
      handler_607: None,
      handler_608: None,
      handler_609: None,
      handler_610: None,
      handler_611: None,
      handler_612: None,
      handler_613: None,
      handler_614: None,
      handler_615: None,
      handler_616: None,
      handler_617: None,
      handler_618: None,
      handler_619: None,
      handler_620: None,
    }
  }
}
